sudo: false

matrix:
  include:
    - env: GHC_VERSION=7.10.1
      addons:
        apt:
          sources:
          - hvr-ghc
          packages:
          - ghc-7.10.1
          - cabal-install-1.22
          - happy
          - alex
      before_install:
      - export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH
    - env: GHC_VERSION=7.8.3
      addons:
        apt:
          sources:
          - hvr-ghc
          packages:
          - ghc-7.8.3
          - cabal-install-1.18
          - happy-1.19.4
          - alex-3.1.3
      before_install:
      - export PATH=/opt/ghc/7.8.3/bin:/opt/cabal/1.18/bin:$PATH
      - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
    - env: GHC_VERSION=7.6.3
      addons:
        apt:
          sources:
          - hvr-ghc
          packages:
          - ghc-7.6.3
          - cabal-install-1.18
          - happy-1.19.4
          - alex-3.1.3
      before_install:
      - export PATH=/opt/ghc/7.6.3/bin:/opt/cabal/1.18/bin:$PATH
      - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH


install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests


script:
 - cabal configure --enable-tests
 - cabal build
 - cabal test